### PR TITLE
OPENE-276 Amended workflow service to be able to start workflow with …

### PR DESCRIPTION
**Pull request by jrudinskij**
Hi Torben,

Could you please review when you get time?

Thanks a lot.

### CODE REVIEW

**Comment by jrudinskij** [comment]
retest this please

**Comment by jrudinskij** [comment]
retest this please

**Comment by syastrov** [comment]
Hi Jurij, I have just fixed the tests that were failing in the develop branch, so we will have to ask Jenkins to... retest this please

**Comment by jrudinskij** [comment]
Hi Seth,
Thanks a million for the fix.

**Pull request merged**
